package game;

public class LiterallyJustTheOpeningCreditsThing {

    static String[] openingCreditsThing = new String[]{
            "Like last thursday or something,",
            "in that one corner of the universe with the rocks,",
            "you know, near that hyperspace bypass,",
            "the one that smells of MS paint,",
            "and has the distinct taste of bad acapella,",
            "down the road, take the third left, then the second right",
            "and down the 31st cul-de-sac you encounter",
            "after you pass SpaceTesco,",
            "not the big SpaceTesco,",
            "the SpaceTesco that used to be a pub until about 8 years or so I guess,",
            "you know the place, that one...",
            "",
            "",
            "",
            "",
            "",
            "",
            "(I can't really put my name here I guess because assignment so uhh)",
            "THE STUDENT WITH ID NUMBER 1804170 PRESENTS...",
            "",
            "",
            "TITLE SCREEN OPENING CRAWL THING",
            "Episode 2.5452353625e+3535453687980970562342463745874684632",
            "THE ONE WITH THE COMPLETE LACK OF IDEAS",
            "",
            "",
            "pretend this says something deep",
            "like idk some sort of epic story",
            "about some intergalactic war in space",
            "(tbh they really should make a film",
            "about something like that at some point.",
            "actually, that's a rather good idea,",
            "imma take a note of it and then",
            "do it when no-one is looking",
            "and then get really really rich from it.",
            "I'm thinking of calling it",
            "'Luminous Spheroid of Plasma Conflict'",
            "let me know if you think that sounds like a nice film name)",
            "Anywho, back to the point at hand",
            "uhh...",
            "",
            "",
            "",
            "oh yeah!",
            "",
            "Inconvenient Space Rocks!",
            "",
            "ok so basically there's a bunch of rocks",
            "and they're being very inconvenient.",
            "",
            "and also they're in space too",
            "",
            "pls shoot them for us k thx bye",
            "and also dont die",
            "",
            "",
            "Oh yeah and also when you destroy the rocks they break into more rocks",
            "but if you leave them alone there's even more pieces",
            "so yeah damned if you do but more damned if you don't",
            "or whatever the phrase is idk",
            "",
            "also they generally keep turning even more red as they approach breaking point",
            "but they are red if they can't break any more so basically",
            "shoot the ones that are turning red before they become red ones",
            "",
            "also I forgot to mention that theres also other people there",
            "and uhh they probably think that we'll give them your salary if they kill you",
            "but we aren't paying you anyway so idk why they're trying",
            "and at this point I just cba to work out what their deal is",
            "but uhh basically try to avoid them thanks",
            "",
            "",
            "",
            "",
            "",
            "you know you can just press any key to skip this, right?",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "bruh",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "According to all known laws of aviation,",
            "there is no way that a rock should be able to fly",
            "unless it weighs 90kg.",
            "in which case you can get a trebuchet to make it fly 300 metres forward",
            "but that's besides the point because how the hecc did these rocks get up here",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "ok so you're probably wondering where I worked out to do this scrolling text thing",
            "basically, on the weekend of 7/3/20-8/3/20, there was a game jam on campus",
            "(society event), I was pretty much the only person who made a game lmao",
            "oh yeah the theme was 'Growth' btw",
            "but yeah I decided to try making a game using the MVC model",
            "(causally throwing excrement at the wall and seeing what stuck, y'know?)",
            "so it was a game where you pretty much had to flail around and hit stuff with a stick",
            "(y'know, very high-brow stuff)",
            "and uhh I decided to try making an intro cutscene before that",
            "kinda decided to try making a type of GameObject",
            "that uses g.drawString() instead of a shape drawing thing",
            "and uhh yeah a bit of spaghet later I got an intro cutscene working",
            "wasn't anywhere near as long or interesting as this one, but it worked I guess",
            "anywho yeah ramble over back to the stupidly long pause between the funny text",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "'PLEASE BECOME FUNNY'",
            "-Ben 'Kylo Ren' Solo, 2020",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "why are you still here? just to suffer?",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "still here?",
            "ok so press p when starting a level",
            "its fun ;)",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "uwu",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "upvotes to the left",
            "edit: we did it, Reddit!"
    };

}
